src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Entity\Picture;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecipeRepository")
 * @UniqueEntity("name")
 */
class Recipe
{
    const COST = [
        1 => 'Économique',
        2 => 'Moyen',
        3 => 'Cher'
    ];

    const DIFFICULTY = [
        1 => 'Facile',
        2 => 'Moyen',
        3 => 'Difficile'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 5,
     *      max = 50
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author = "Cécile";

    /**
     * @ORM\Column(type="smallint")
     */
    private $cookingTime;

    /**
     * @ORM\Column(type="smallint")
     */
    private $cost;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="smallint")
     */
    private $difficulty;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Positive
     */
    private $numberPersons;

    /**
     * @ORM\Column(type="smallint")
     */
    private $preparationTime;

    /**
     * @ORM\Column(type="smallint")
     */
    private $totalTime;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="recipes")
     */
    private $options;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\DishType", inversedBy="recipes")
     */
    private $DishTypes;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\FoodType", inversedBy="recipes")
     */
    private $foodTypes;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="recipe", fetch="EAGER", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(
     *      mimeTypes="image/jpeg",
     *      mimeTypesMessage="Images acceptées en format .jpg")
     * })
     */
    private $pictureFiles;

    /**
     * @var null|Picture
     */
    private $picture;

    /**
     * @ORM\Column(type="text")
     */
    private $steps;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MealPlanning", mappedBy="recipe", orphanRemoval=true)
     */
    private $mealPlannings;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\RecipeIngredients", mappedBy="recipe", orphanRemoval=true, fetch="EAGER", cascade={"persist"})
     */
    private $recipeIngredients;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->options = new ArrayCollection();
        $this->DishTypes = new ArrayCollection();
        $this->foodTypes = new ArrayCollection();
        $this->pictures = new ArrayCollection();
        $this->mealPlannings = new ArrayCollection();
        $this->recipeIngredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->name);
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cookingTime;
    }

    public function setCookingTime(int $cookingTime): self
    {
        $this->cookingTime = $cookingTime;

        return $this;
    }

    public function getCost(): ?int
    {
        return $this->cost;
    }

    public function getCostType(): ?string
    {
        return self::COST[$this->cost];
    }

    public function setCost(int $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function getDifficultyType(): ?string
    {
        return self::DIFFICULTY[$this->difficulty];
    }

    public function setDifficulty(int $difficulty): self
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getNumberPersons(): ?int
    {
        return $this->numberPersons;
    }

    public function setNumberPersons(int $numberPersons): self
    {
        $this->numberPersons = $numberPersons;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparationTime;
    }

    public function setPreparationTime(int $preparationTime): self
    {
        $this->preparationTime = $preparationTime;

        return $this;
    }

    public function getTotalTime(): ?int
    {
        return $this->totalTime;
    }

    public function setTotalTime(int $totalTime): self
    {
        $this->totalTime = $totalTime;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->options->contains($option)) {
            $this->options[] = $option;
            $option->addRecipe($this);
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->options->contains($option)) {
            $this->options->removeElement($option);
            $option->removeRecipe($this);
        }

        return $this;
    }

    /**
     * @return Collection|DishType[]
     */
    public function getDishTypes(): Collection
    {
        return $this->DishTypes;
    }

    public function addDishType(DishType $dishType): self
    {
        if (!$this->DishTypes->contains($dishType)) {
            $this->DishTypes[] = $dishType;
        }

        return $this;
    }

    public function removeDishType(DishType $dishType): self
    {
        if ($this->DishTypes->contains($dishType)) {
            $this->DishTypes->removeElement($dishType);
        }

        return $this;
    }

    /**
     * @return Collection|FoodType[]
     */
    public function getFoodTypes(): Collection
    {
        return $this->foodTypes;
    }

    public function addFoodType(FoodType $foodType): self
    {
        if (!$this->foodTypes->contains($foodType)) {
            $this->foodTypes[] = $foodType;
        }

        return $this;
    }

    public function removeFoodType(FoodType $foodType): self
    {
        if ($this->foodTypes->contains($foodType)) {
            $this->foodTypes->removeElement($foodType);
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * setPictureFiles
     * @param  mixed $pictureFiles
     * @return self
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile)
        {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function getPicture(): ?Picture
    {
        if($this->pictures->isEmpty())
        {
            return null;
        } 
        return $this->pictures->first();
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setRecipe($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getRecipe() === $this) {
                $picture->setRecipe(null);
            }
        }

        return $this;
    }

    public function getSteps(): ?string
    {
        return $this->steps;
    }

    public function setSteps(string $steps): self
    {
        $this->steps = $steps;

        return $this;
    }

    public function __toString() 
    {
        return $this->name;
    }

    /**
     * @return Collection|MealPlanning[]
     */
    public function getMealPlannings(): Collection
    {
        return $this->mealPlannings;
    }

    public function addMealPlanning(MealPlanning $mealPlanning): self
    {
        if (!$this->mealPlannings->contains($mealPlanning)) {
            $this->mealPlannings[] = $mealPlanning;
            $mealPlanning->setRecipe($this);
        }

        return $this;
    }

    public function removeMealPlanning(MealPlanning $mealPlanning): self
    {
        if ($this->mealPlannings->contains($mealPlanning)) {

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Option;
use App\Entity\Recipe;
use App\Entity\DishType;
use App\Entity\FoodType;
use App\Form\RecipeIngredientsType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('pictureFiles', FileType::class, [
                'required' => false,
                'multiple' => true
            ])
            ->add('cookingTime')
            ->add('cost', ChoiceType::class, [
                "choices" => $this->getCostChoices()
            ])
            ->add('difficulty', ChoiceType::class, [
                "choices" => $this->getDifficultyChoices()
            ])
            ->add('numberPersons')
            ->add('preparationTime')
            ->add('totalTime')
            ->add('DishTypes', EntityType::class, [
                'class' => DishType::class,
                'choice_label' => 'name',
                'multiple' => true
            ])
            ->add('foodTypes', EntityType::class, [
                'class' => FoodType::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('options', EntityType::class, [
                'class' => Option::class,
                'choice_label' => 'name',
                'multiple' => true,
                'required' => false
            ])
            ->add('steps')
            ->add('recipeIngredients', CollectionType::class, [
                'entry_type' => RecipeIngredientsType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
            'translation_domain' => 'forms'
        ]);
    }

    private function getCostChoices()
    {
        $choices = Recipe::COST;
        return $this->getChoices($choices);
    }

    private function getDifficultyChoices()
    {
        $choices = Recipe::DIFFICULTY;
        return $this->getChoices($choices);
    }

    private function getChoices($var)
    {
        $output = [];
        foreach($var as $k => $v)
        {
            $output[$v] = $k;
        }
        return $output;
    }
}

templates/recipe/_recipe.html.twig
<div class="card mb-4 recipeCard">
    {% if recipe.picture %}
        <img src="{{ vich_uploader_asset(recipe.picture, "imageFile") | imagine_filter('thumb') }}" alt="card-img-top">
    {% else %}
        <img src="{{ "empty.jpg" | imagine_filter('thumb') }}" alt="card-img-top">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ path('recipe.show', {id: recipe.id, slug: recipe.slug}) }}">{{ recipe.name }}</a>
        </h5>
        <p class="card-text">
            {% for dishType in recipe.DishTypes %}
                {{ dishType.name }}
            {% endfor %}
        <br>
        {{ recipe.totalTime }} minutes<br>
        {{ recipe.numberPersons }} {% if recipe.numberPersons > 1 %} personnes {% else %} personne {% endif %}</p>
    </div>
</div>

templates/recipe/index.html.twig
{% extends "base.html.twig" %}

{% block title 'Voir toutes mes recettes' %}

{% block stylesheets %}
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block body %}
    <div class="recipesIndex">
        <div class="jumbotron">
            <div class="container">
                {{ form_start(form) }}
                <div class="form-row align-items-end">
                    <div class="col-md-2 col-6">
                        {{ form_row(form.maxTotalTime) }}
                    </div>
                    <div class="col-md-2 col-6">
                        {{ form_row(form.numberPersons) }}
                    </div>
                    <div class="col-md-2 col-6">
                        {{ form_row(form.DishTypes) }}
                    </div>
                    <div class="col-md-2 col-6">
                        {{ form_row(form.foodTypes) }}
                    </div>
                    <div class="col-md-2 col-6">
                        {{ form_row(form.options) }}
                    </div>
                    <div class="col-md-2 col-6">
                        <div class="form-group">
                            <button class="btn btn-primary">Rechercher</button>
                        </div>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        </div>

        <div class="container mt-4">
            <h1 class="h1 allRecipes">Toutes mes recettes</h1>

            <div class="allRecipes">
                {% for recipe in recipes %}
                    {% include "recipe/_recipe.html.twig" %}
                {% endfor %}
            </div>

            <div class="pagination">
                {{ knp_pagination_render(recipes) }}
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {{ encore_entry_script_tags('allRecipes') }}
{% endblock %}

templates/recipe/show.html.twig
{% extends "base.html.twig" %}

{% block title "Ma recette de " ~ recipe.name %}

{% block body %}
    <div class="container mt-5" id="allBlockRecipe">

        <div class="row" id="blocRecipe">
            <div id="divImg" class="col-md-5 col-sm-5 col-10">
                <div data-slider>
                    {% if recipe.pictures is empty %}
                        <img src="{{ 'empty.jpg' | imagine_filter('medium') }}" alt="card-img-top">
                    {% else %}
                        {% for picture in recipe.pictures %}
                            <img src="{{ vich_uploader_asset(picture, 'imageFile') | imagine_filter('medium') }}" alt="card-img-top">
                        {% endfor %}
                    {% endif %}
                </div> 
            </div>
            <div id="contentRecipe" class="col-md-6 col-sm-6 col-12">
                <h1>{{ recipe.name }}</h1>
                <div id="detailsRecipe">
                    <p>Type : 
                        {% for dishType in recipe.DishTypes %}
                                <span><b>{{ dishType.name }}</b></span>
                        {% endfor %}
                    </p>
                    <p>Cuisine : 
                        {% for foodType in recipe.foodTypes %}
                            <span ><b>{{ foodType.name }}</b></span>
                        {% endfor %}
                    </p>
                    <p>Niveau de difficulté : <b>{{recipe.difficultyType}}</b></p>
                    <p>Coût : <b>{{recipe.costType}}</b></p>
                    <div class="row">
                        <p class="col-4">Total :<br><b>{{recipe.totalTime}}</b> min</p>
                        <p class="col-4">Préparation :<br><b>{{recipe.preparationTime}}</b> min</p>
                        <p class="col-4">Cuisson :<br><b>{{recipe.cookingTime}}</b> min</p>
                    </div>
                    {% for option in recipe.options %}
                        <p><b>{{ option.name }}</b></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row" id="ingredientsAndDescription">
            <div id="ingredients" class="col-md-4 col-sm-4 col-12">
                <h2>Ingrédients</h2>
                <ul>
                    {% for ingredient in recipe.recipeIngredients %}
                        <li>{{ ingredient.quantity }} {{ ingredient.unit }} {{ ingredient.nameIngredient }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div id="recipeDescription" class="col-md-7 col-sm-7 col-12">
                <h2>Description de la recette</h2><br><p>{{recipe.steps|nl2br}}</p>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    {{ parent() }}
{% endblock %}

{% block javascripts %}
   {{ encore_entry_script_tags('app') }}
   {{ encore_entry_script_tags('allRecipes') }}
   <script src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
   <script>
   $(document).ready(function() { 
    $('[data-slider]').slick({
        dots: true,
        arrows: true
    });
    });
    </script>
{% endblock %}